### ISSUE TITLE
Wild Posts - Category issue

### ISSUE THREAD

**Issue by TeckniX** [klevo/wildflower#11]
I'm pretty new to the hasMany setup, but it seems that if a blog post is updated, then it loses its category association.

I'm not sure what is missing, but basically the original hidden element isn't being populated with the WildCategory variable.

**Comment by TeckniX** [comment]
W00t this has been fixed. 
The issue was that on page-load the JS wasn't grabbing the dropdown value. 
By default upon binding it will do that now.

**Comment by majic3** [comment]
fixed but left open - so now closed
