### ISSUE TITLE
Validation not working correctly when adding or editing users

### ISSUE THREAD

**Issue by mikebirch** [klevo/wildflower#14]
Validation of the login field isn't working in wildflower/models/wild_user.php
It always displays the error message "Login must be between 5 to 50 alphanumeric characters long"

**Comment by TeckniX** [comment]
mike, 
can you include your wf version and where you got the code? github or zip dowbload?

**Comment by mikebirch** [comment]
I'm using klevo-wildflower-853920c from github.  wildflower/models/user.php
I have done some more testing and the problem seems to be with CakePHP 1.2.5 rather than Wildflower.  I'm using PHP 5.2.5 and the alphaNumeric validation always fails regardless of the input.  I have used custom validation instead http://book.cakephp.org/view/150/Custom-Validation-Rules

**Comment by TeckniX** [comment]
Yup I had the same issue - ended up fixing it with the following:

<pre>
login' => array(
                'rule' => array('custom', '/^[a-z0-9_.]{5,50}$/i'),
                'required' => true,
                'message' => 'Login must be between 5 to 50 alphanumeric characters long'
        )
</pre>

**Comment by majic3** [comment]
seems ok now - with validation rule left as is.  Anyone find any troubles?
