### ISSUE TITLE
JLM load time

### ISSUE THREAD

**Issue by TeckniX** [klevo/wildflower#15]
I think we need to re-think how the JLM can be used. Currently it reminds me of the old 'ExtJS' which honestly doesn't work well and is very bulky.

Currently the JLM is 211kb, which is a LOT more than most would like to see on a page load. There is a definite slowdown when it tries to load that file and apply the JS that it combines. 
Is there a way we could lighten things up? Or perhaps do away with it?

**Comment by klevo** [comment]
I agree.

To lighten it up we can remove some vendors/ like jquery UI, but we need to make sure the core is not using it. I actually always end up using the stuff that's in vendors/ on my projects so that's why it's there.

But keep in mind that the whole point of JLM, is to load ALL the stuff on one pass, in one file - when you frist visit the site. From that point every modern device cashes the JS.

**Comment by klevo** [comment]
...all the other functionality deals mainly with allowing you to control what to load when based on controller/action which is awesome with CakePHP projects. It may seem bulky because of some of the vendors, but it's really just a small trick that does a lot of work for you :)

**Comment by TeckniX** [comment]
I really do like the JLM, I just don't like the fact that it loads close to 1MB total of plugins and such. I have an ok question, but 1MB every time really sucks.

Would it be possible to create an enable/disable panel for all jlm components?
jquery UI has some nice stuff, but I don't see where it's used right away. 

Perhaps we could make a list of all plugins, figure out what people can deal with or without and go from there?

**Comment by majic3** [comment]
I have some ideas for JLM.

Be able to load a base of jlm core functions; be able to load additional scripts

Save output of JLM to app/wildflower/js/jlm/jlm.PACK.js

where PACK is the jlm package token

Adding Inflections.js to JLM is powerful - JLM may benefit from an overhaul using model pluralisation clientside much more akin to what cake does serverside.   I can easily make elements reusable throughout wfAdmin.
