### ISSUE TITLE
Custom Wildflower.prefix causes WfController controller errors with revisions

### ISSUE THREAD

**Issue by nihiloRex** [klevo/wildflower#8]
Using a custom Wildflower.prefix causes "Missing WF Controller" error when viewing revisions. If you do not change the Wildflower.prefix, this is not an issue.

**Comment by TeckniX** [comment]
If you look on the forum, there has been a couple of revisions to this - I currently have a custom wf prefix and have everything working without any problems.

http://forums.wf.klevo.sk/
