### ISSUE TITLE
Widget update

### ISSUE THREAD

**Issue by TeckniX** [klevo/wildflower#9]
When saving out a widget, a missing view is sent back in the ajax post response

**Comment by TeckniX** [comment]
This can be easily fixed by adding the following:
line: 61
$this->autoRender = false;
in wildflower/controllers/wild_widgets_controller.php
for the wf_update() function

**Comment by majic3** [comment]
this looks ok to me in the back to convetions branch

**Comment by TeckniX** [comment]
this was in the original master- probably has been fixed in the newer branch.

Thanks for checking it though!
